# Generated by Django 5.0.6 on 2026-07-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_groups_user_user_permissions'),
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_leagues',
            field=models.ManyToManyField(blank=True, related_name='followers', to='predictions.league'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_teams',
            field=models.ManyToManyField(blank=True, related_name='fans', to='predictions.team'),
        ),
    ]
