# Generated by Django 5.0.6 on 2026-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_favorite_leagues_user_favorite_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=2),
        ),
    ]
