# Generated by Django 5.0.6 on 2026-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tip_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='tip_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_tipster',
            field=models.BooleanField(default=False),
        ),
    ]
