# Generated by Django 5.0.6 on 2026-08-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_followers_count_user_following_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipster_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
