# Generated by Django 5.0.6 on 2026-08-21 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0012_alter_teamstanding_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tips', models.PositiveIntegerField(db_index=True, default=0)),
                ('correct_tips', models.PositiveIntegerField(default=0)),
                ('incorrect_tips', models.PositiveIntegerField(default=0)),
                ('void_tips', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(db_index=True, default=0.0)),
                ('tips_1x2', models.PositiveIntegerField(default=0)),
                ('correct_1x2', models.PositiveIntegerField(default=0)),
                ('accuracy_1x2', models.FloatField(default=0.0)),
                ('tips_btts', models.PositiveIntegerField(default=0)),
                ('correct_btts', models.PositiveIntegerField(default=0)),
                ('accuracy_btts', models.FloatField(default=0.0)),
                ('tips_over_under', models.PositiveIntegerField(default=0)),
                ('correct_over_under', models.PositiveIntegerField(default=0)),
                ('accuracy_over_under', models.FloatField(default=0.0)),
                ('tips_double_chance', models.PositiveIntegerField(default=0)),
                ('correct_double_chance', models.PositiveIntegerField(default=0)),
                ('accuracy_double_chance', models.FloatField(default=0.0)),
                ('current_streak', models.PositiveSmallIntegerField(default=0)),
                ('best_streak', models.PositiveSmallIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('total_upvotes_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tip_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tip Performance',
                'verbose_name_plural': 'Tip Performances',
                'db_table': 'tips_tipperformance',
            },
        ),
        migrations.CreateModel(
            name='UserTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_key', models.CharField(help_text="e.g., '1X2', 'OVER_UNDER_2_5', 'BTTS', 'DRAW_NO_BET'", max_length=50)),
                ('selection', models.CharField(help_text="e.g., 'home_win', 'over_2.5', 'both_teams_score_yes'", max_length=50)),
                ('confidence', models.PositiveSmallIntegerField(default=50, help_text='User confidence 0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reasoning', models.TextField(blank=True, default='', help_text="User's analysis or reasoning for this tip")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect'), ('VOID', 'Void')], db_index=True, default='PENDING', max_length=10)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FOLLOWERS', 'Followers Only'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=10)),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('upvotes_count', models.PositiveIntegerField(default=0)),
                ('downvotes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(help_text='Match this tip is for', on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='predictions.match')),
                ('user', models.ForeignKey(help_text='User who created this tip', on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Tip',
                'verbose_name_plural': 'User Tips',
                'db_table': 'tips_usertip',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_votes', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tips.usertip')),
            ],
            options={
                'verbose_name': 'Tip Vote',
                'verbose_name_plural': 'Tip Votes',
                'db_table': 'tips_tipvote',
            },
        ),
        migrations.CreateModel(
            name='TipShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_to', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('COPY', 'Copy Link'), ('SMS', 'SMS')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip_shares', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tips.usertip')),
            ],
            options={
                'verbose_name': 'Tip Share',
                'verbose_name_plural': 'Tip Shares',
                'db_table': 'tips_tipshare',
            },
        ),
        migrations.CreateModel(
            name='TipComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tips.tipcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_comments', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tips.usertip')),
            ],
            options={
                'verbose_name': 'Tip Comment',
                'verbose_name_plural': 'Tip Comments',
                'db_table': 'tips_tipcomment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usertip',
            index=models.Index(fields=['user', '-created_at'], name='tips_userti_user_id_d64f37_idx'),
        ),
        migrations.AddIndex(
            model_name='usertip',
            index=models.Index(fields=['match', '-created_at'], name='tips_userti_match_i_eb8a02_idx'),
        ),
        migrations.AddIndex(
            model_name='usertip',
            index=models.Index(fields=['status', '-created_at'], name='tips_userti_status_2ffaa8_idx'),
        ),
        migrations.AddIndex(
            model_name='usertip',
            index=models.Index(fields=['visibility', '-created_at'], name='tips_userti_visibil_eb4509_idx'),
        ),
        migrations.AddIndex(
            model_name='usertip',
            index=models.Index(fields=['market_key', '-created_at'], name='tips_userti_market__b11019_idx'),
        ),
        migrations.AddIndex(
            model_name='usertip',
            index=models.Index(fields=['views_count', '-created_at'], name='tips_userti_views_c_15caff_idx'),
        ),
        migrations.AddIndex(
            model_name='usertip',
            index=models.Index(fields=['upvotes_count', '-created_at'], name='tips_userti_upvotes_8725e4_idx'),
        ),
        migrations.AddIndex(
            model_name='tipvote',
            index=models.Index(fields=['tip', '-created_at'], name='tips_tipvot_tip_id_cc35e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tipvote',
            index=models.Index(fields=['user', '-created_at'], name='tips_tipvot_user_id_61e2e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipvote',
            unique_together={('tip', 'user')},
        ),
        migrations.AddIndex(
            model_name='tipshare',
            index=models.Index(fields=['tip', '-created_at'], name='tips_tipsha_tip_id_e59487_idx'),
        ),
        migrations.AddIndex(
            model_name='tipcomment',
            index=models.Index(fields=['tip', '-created_at'], name='tips_tipcom_tip_id_49f7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tipcomment',
            index=models.Index(fields=['user', '-created_at'], name='tips_tipcom_user_id_b63157_idx'),
        ),
        migrations.AddIndex(
            model_name='tipcomment',
            index=models.Index(fields=['parent', '-created_at'], name='tips_tipcom_parent__cc1bd3_idx'),
        ),
    ]
