# Generated by Django 5.0.6 on 2026-08-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipAISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(help_text='Version of the model used for this prediction', max_length=50)),
                ('prediction_generated_at', models.DateTimeField(help_text='When the prediction was generated')),
                ('market_key', models.CharField(help_text='Market key from prediction', max_length=50)),
                ('selection_key', models.CharField(help_text='Selection key from prediction', max_length=50)),
                ('raw_probability', models.FloatField(blank=True, help_text='Raw model probability (0-1)', null=True)),
                ('calibrated_probability', models.FloatField(blank=True, help_text='Calibrated probability if available (0-1)', null=True)),
                ('recommendation_tier', models.CharField(blank=True, help_text='STRONG, ELITE, or NO_STRONG_PICK', max_length=20, null=True)),
                ('data_quality', models.FloatField(blank=True, help_text='Data quality score (0-1)', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score (0-1)', null=True)),
                ('ai_agrees', models.BooleanField(default=False, help_text='Whether tip selection matches AI recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_snapshot', to='tips.usertip')),
            ],
            options={
                'verbose_name': 'Tip AI Snapshot',
                'verbose_name_plural': 'Tip AI Snapshots',
                'db_table': 'tips_taisnapshot',
            },
        ),
    ]
