# Generated by Django 5.0.6 on 2026-08-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tipaisnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertip',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
