# Generated by Django 5.0.6 on 2026-08-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_usertip_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipperformance',
            name='accuracy_dnb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='correct_dnb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='recent_form_correct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='recent_form_tips',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='tips_dnb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
