# Generated by Django 5.0.6 on 2026-08-29 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_tipperformance_accuracy_dnb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], db_index=True, default='PENDING', max_length=10)),
                ('total_legs', models.PositiveSmallIntegerField(default=0)),
                ('won_legs', models.PositiveSmallIntegerField(default=0)),
                ('lost_legs', models.PositiveSmallIntegerField(default=0)),
                ('void_legs', models.PositiveSmallIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('upvotes_count', models.PositiveIntegerField(default=0)),
                ('downvotes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tip Slip',
                'verbose_name_plural': 'Tip Slips',
                'db_table': 'tips_tipslip',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipSlipLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect'), ('VOID', 'Void')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='tips.tipslip')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_legs', to='tips.usertip')),
            ],
            options={
                'verbose_name': 'Tip Slip Leg',
                'verbose_name_plural': 'Tip Slip Legs',
                'db_table': 'tips_tipslipeg',
            },
        ),
        migrations.AddIndex(
            model_name='tipslip',
            index=models.Index(fields=['creator', '-created_at'], name='tips_tipsli_creator_8dd9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='tipslip',
            index=models.Index(fields=['status', '-created_at'], name='tips_tipsli_status_24df1e_idx'),
        ),
        migrations.AddIndex(
            model_name='tipslipleg',
            index=models.Index(fields=['slip', '-created_at'], name='tips_tipsli_slip_id_addcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='tipslipleg',
            index=models.Index(fields=['tip'], name='tips_tipsli_tip_id_55a28d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipslipleg',
            unique_together={('slip', 'tip')},
        ),
    ]
