# Generated by Django 5.0.6 on 2026-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_tipslip_tipslipleg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipperformance',
            name='accuracy_bundesliga',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='accuracy_epl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='accuracy_laliga',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='accuracy_ligue1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='accuracy_seriea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='correct_bundesliga',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='correct_epl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='correct_laliga',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='correct_ligue1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='correct_seriea',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='tips_bundesliga',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='tips_epl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='tips_laliga',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='tips_ligue1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='tips_seriea',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
