# Generated by Django 5.0.6 on 2026-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_tipperformance_accuracy_bundesliga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipperformance',
            name='tipster_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='tipperformance',
            name='tipster_score_version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
    ]
