# Generated by Django 5.0.6 on 2026-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_tipperformance_tipster_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertip',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this tip is still active/visible in main feed'),
        ),
    ]
