# Generated by Django 5.0.6 on 2026-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DAILY_PICKS', 'Daily Picks'), ('FAVORITE_TEAM_MATCH', 'Favorite Team Match'), ('HIGH_CONFIDENCE', 'High Confidence Alert'), ('RESULT', 'Result'), ('SUPPORT_REPLY', 'Support Reply')], max_length=30),
        ),
    ]
