# Generated by Django 5.0.6 on 2026-07-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DAILY_PICKS', 'Daily Picks'), ('FAVORITE_TEAM_MATCH', 'Favorite Team Match'), ('HIGH_CONFIDENCE', 'High Confidence Alert'), ('RESULT', 'Result'), ('SUPPORT_REPLY', 'Support Reply'), ('MIC_WINNER', 'Mic Winner')], max_length=30),
        ),
    ]
