# Generated by Django 5.0.6 on 2026-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='evening_recap_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='live_match_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='morning_picks_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='weekly_summary_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DAILY_PICKS', 'Daily Picks'), ('FAVORITE_TEAM_MATCH', 'Favorite Team Match'), ('HIGH_CONFIDENCE', 'High Confidence Alert'), ('RESULT', 'Result'), ('SUPPORT_REPLY', 'Support Reply'), ('MIC_WINNER', 'Mic Winner'), ('MORNING_PICKS', 'Morning Picks'), ('LIVE_MATCH_ALERT', 'Live Match Alert'), ('EVENING_RECAP', 'Evening Recap'), ('WEEKLY_SUMMARY', 'Weekly Summary')], max_length=30),
        ),
    ]
