# Generated by Django 5.0.6 on 2026-07-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('positive', 'Positive'), ('negative', 'Negative')], default=None, max_length=10, null=True),
        ),
    ]
