# Generated by Django 5.0.6 on 2026-07-08 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0002_activederby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveSmallIntegerField()),
                ('mood', models.CharField(choices=[('FUNNY', '😂 Funny'), ('FIRE', '🔥 Fire'), ('ANGRY', '😡 Angry'), ('RESPECT', '👏 Respect'), ('SHOCK', '🤯 Shock'), ('PAIN', '💔 Pain')], max_length=10)),
                ('team_side', models.CharField(choices=[('HOME', 'Home Team Fan'), ('AWAY', 'Away Team Fan'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Admin anaweza kuzima video isiyofaa')),
                ('is_fan_of_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mic_reactions', to='predictions.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mic_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mic_reaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MicReactionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('LAUGH', '😂'), ('FIRE', '🔥'), ('CLAP', '👏'), ('HUNDRED', '💯'), ('ROFL', '🤣')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mic_reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mic.micreaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mic_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mic_reactionvote',
                'unique_together': {('mic_reaction', 'user')},
            },
        ),
    ]
