# Generated by Django 5.0.6 on 2026-07-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('cta_label', models.CharField(blank=True, default='Angalia', max_length=50)),
                ('route', models.CharField(blank=True, default='', max_length=200)),
                ('accent_color', models.CharField(default='#00FF87', max_length=7)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'herocarousel_customslide',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
