# Generated by Django 5.0.6 on 2026-07-07 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BAN_USER', 'Ban User'), ('UNBAN_USER', 'Unban User'), ('MANUAL_SUBSCRIPTION', 'Manual Subscription Activation'), ('DEACTIVATE_CARD', 'Deactivate Card'), ('ACTIVATE_CARD', 'Activate Card'), ('TOGGLE_BIG_MATCH', 'Toggle Big Match'), ('BROADCAST_NOTIFICATION', 'Broadcast Notification'), ('CREATE_MATCH', 'Create Match'), ('UPDATE_MATCH', 'Update Match'), ('MAKE_ADMIN', 'Make Admin'), ('REVOKE_ADMIN', 'Revoke Admin')], max_length=30)),
                ('target_description', models.CharField(help_text="mfano: 'User #42 (+255712345678)'", max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_adminactionlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
