# Generated by Django 5.0.6 on 2026-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tigo_auth_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tigo_redirect_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tigo_transaction_ref_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
