# Generated by Django 5.0.6 on 2026-07-09 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('ACCOUNT_ISSUE', 'Tatizo la Akaunti'), ('PAYMENT_ISSUE', 'Tatizo la Malipo'), ('CONTENT_REPORT', 'Ripoti ya Maudhui'), ('BUG_REPORT', 'Hitilafu ya App'), ('FEEDBACK', 'Maoni'), ('OTHER', 'Nyingine')], max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('related_content_type', models.CharField(blank=True, choices=[('MIC_REACTION', 'Bashiri Mic Video'), ('USER_PREDICTION_CARD', 'User Prediction'), ('ROOM_MESSAGE', 'Match Room Message')], default='', max_length=25)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_ticket',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], max_length=6)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('MIC_REACTION', 'Bashiri Mic Video'), ('USER_PREDICTION_CARD', 'User Prediction'), ('ROOM_MESSAGE', 'Match Room Message')], max_length=25)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('ABUSIVE', 'Matusi'), ('INAPPROPRIATE', 'Maudhui Yasiyofaa'), ('SPAM', 'Spam'), ('OTHER', 'Nyingine')], max_length=15)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_contentreport',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'content_type', 'object_id')},
            },
        ),
    ]
