# Generated by Django 5.0.6 on 2026-08-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='content_type',
            field=models.CharField(choices=[('MIC_REACTION', 'Bashiri Mic Video'), ('ROOM_MESSAGE', 'Match Room Message')], max_length=25),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='related_content_type',
            field=models.CharField(blank=True, choices=[('MIC_REACTION', 'Bashiri Mic Video'), ('ROOM_MESSAGE', 'Match Room Message')], default='', max_length=25),
        ),
    ]
