# Generated by Django 5.0.6 on 2026-07-06 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AI_PICK', 'AI Pick'), ('LIVE_MATCH', 'Live Match'), ('RESULT_RECAP', 'Result Recap'), ('AI_WEEKLY_REPORT', 'AI Weekly Report'), ('USER_PREDICTION', 'User Prediction'), ('STAT', 'Stat/Insight'), ('POLL', 'Poll/Vote'), ('MILESTONE', 'Milestone')], db_index=True, max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='predictions.match')),
            ],
            options={
                'db_table': 'feed_card',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=30)),
                ('selection', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=150)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_predictions', to='predictions.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_userprediction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='feed.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_pollvote',
                'unique_together': {('card', 'user')},
            },
        ),
    ]
