# Generated by Django 5.0.6 on 2026-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('AI_PICK', 'AI Pick'), ('LIVE_MATCH', 'Live Match'), ('RESULT_RECAP', 'Result Recap'), ('AI_WEEKLY_REPORT', 'AI Weekly Report'), ('USER_PREDICTION', 'User Prediction'), ('STAT', 'Stat/Insight'), ('POLL', 'Poll/Vote'), ('MILESTONE', 'Milestone'), ('DID_YOU_KNOW', 'Did You Know'), ('DEBATE', 'Debate'), ('MIC_WINNER', 'Mic Winner')], db_index=True, max_length=20),
        ),
    ]
