# Generated by Django 5.0.6 on 2026-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprediction',
            name='matched_ai_pick',
            field=models.BooleanField(default=False, help_text='True ikiwa selection ya mtumiaji inalingana na AI recommendation ya soko hilo — imehesabiwa server-side wakati wa kuunda.'),
        ),
    ]
