# Generated by Django 5.0.6 on 2026-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_userprediction_matched_ai_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('AI_PICK', 'AI Pick'), ('LIVE_MATCH', 'Live Match'), ('RESULT_RECAP', 'Result Recap'), ('AI_WEEKLY_REPORT', 'AI Weekly Report'), ('STAT', 'Stat/Insight'), ('POLL', 'Poll/Vote'), ('MILESTONE', 'Milestone'), ('DID_YOU_KNOW', 'Did You Know'), ('DEBATE', 'Debate'), ('MIC_WINNER', 'Mic Winner')], db_index=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='UserPrediction',
        ),
    ]
