# Generated by Django 5.0.6 on 2026-09-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_card_type_delete_userprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('AI_PICK', 'AI Pick'), ('LIVE_MATCH', 'Live Match'), ('RESULT_RECAP', 'Result Recap'), ('AI_WEEKLY_REPORT', 'AI Weekly Report'), ('STAT', 'Stat/Insight'), ('POLL', 'Poll/Vote'), ('MILESTONE', 'Milestone'), ('DID_YOU_KNOW', 'Did You Know'), ('DEBATE', 'Debate'), ('MIC_WINNER', 'Mic Winner'), ('BEST_STREAK_USER', 'Best Streak User')], db_index=True, max_length=20),
        ),
    ]
